;; -*- coding: utf-8-unix -*-
;; History for SLIME REPL. Automatically written.
;; Edit only if you know what you're doing
("(clear)" "(select (where :artist \"Joji Miller\"))" "(load-db \"3-a-simple-database.db\")" "(load-db 3-a-simple-database.db)" "(format t \"~@r\" 4611686018427387903)" "(format t \"~:r\" 4611686018427387903)" "(format t \"~r\" 4611686018427387903)" "(format t \"~:@r\" 4611686018427387903)" "call-arguments-limit" "(call-arguments-limit)")